authorized:
  - name: Cliente-Demo (representa tu VM Kali)
    ip: 10.0.2.15
    mac: "08:00:27:aa:bb:15"

  - name: Gateway-NAT
    ip: 10.0.2.2
    mac: "52:54:00:12:35:02"

  - name: DNS-NAT
    ip: 10.0.2.3
    mac: "52:54:00:12:35:03"
